server:
  port: 8080

spring:
  application:
    name: raceflow-api-gateway
  cloud:
    gateway:
      routes: []


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: local
